// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQY_792qjSL52d3AwCjdaBaI8Mc9Z3dxY',
    appId: '1:24678525743:web:cce44be5b46eb0e8ba4fda',
    messagingSenderId: '24678525743',
    projectId: 'signup-login-9679a',
    authDomain: 'signup-login-9679a.firebaseapp.com',
    storageBucket: 'signup-login-9679a.appspot.com',
    measurementId: 'G-11GV0PJ1BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4zw43SKawCsPLSjjsR6KPbc6EsxebdpU',
    appId: '1:24678525743:android:53522978a882c93bba4fda',
    messagingSenderId: '24678525743',
    projectId: 'signup-login-9679a',
    storageBucket: 'signup-login-9679a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhr_Y6hSsnSgXUtJyyU6RAGBK4UeJSbuY',
    appId: '1:24678525743:ios:c8b535cdac0c9e23ba4fda',
    messagingSenderId: '24678525743',
    projectId: 'signup-login-9679a',
    storageBucket: 'signup-login-9679a.appspot.com',
    iosClientId: '24678525743-vvp7bvpmia2luor47mmar4atmlmuq18e.apps.googleusercontent.com',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhr_Y6hSsnSgXUtJyyU6RAGBK4UeJSbuY',
    appId: '1:24678525743:ios:c8b535cdac0c9e23ba4fda',
    messagingSenderId: '24678525743',
    projectId: 'signup-login-9679a',
    storageBucket: 'signup-login-9679a.appspot.com',
    iosClientId: '24678525743-vvp7bvpmia2luor47mmar4atmlmuq18e.apps.googleusercontent.com',
    iosBundleId: 'com.example.testproject',
  );
}
